version: 0.0.0.{build}
image: Visual Studio 2019
skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - .github/*
    - .paket/*
    - '**/*.md'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(appveyor_build_version)'
  package_version: '$(appveyor_build_version)'
  assembly_version: '$(appveyor_build_version)'
  file_version: '$(appveyor_build_version)'
  informational_version: '$(appveyor_build_version)'
build_script:
- cmd: >-
    dotnet tool restore
    
    dotnet pack src\PaketChain.sln --configuration Release
test: off
artifacts:
- path: src\PaketChain\nupkg\PaketChain.$(appveyor_build_version).nupkg
  name: PaketChain.$(appveyor_build_version).nupkg
deploy:
- provider: NuGet
  api_key:
    secure: en+66W6nW/JqtNDDIEeRUwdWFjw2YsKBj614gISiX+UXcgUfTvUV+ct9ZPpez1qY
  artifact: PaketChain.$(appveyor_build_version).nupkg
  on:
    branch: master
